apiVersion: v2
name: argocd
description: Chart managing Argo CD installation

type: application
version: 0.1.0
appVersion: "3.3.0"

dependencies:
- name: argo-cd
  version: "9.4.1"
  repository: "https://argoproj.github.io/argo-helm"